Repository kubewarden/audit-scanner, pull requests merged in 2023-06, with the labels that each got.

#40 feat: Add report package, print reports to stdout
  .github/workflows/container-build.yml
  CONTRIBUTING.md
  Makefile
  cmd/root.go
  config/README.md
  config/crd/wgpolicyk8s.io_clusterpolicyreports.yaml
  config/crd/wgpolicyk8s.io_policyreports.yaml
  go.mod
  go.sum
  internal/constants/constants.go
  internal/policies/fetcher.go
  internal/policies/fetcher_test.go
  internal/report/constants.go
  internal/report/doc.go
  internal/report/report.go
  internal/report/store.go
  internal/report/store_test.go
  internal/resources/fetcher.go
  internal/resources/fetcher_test.go
  internal/scanner/scanner.go
Labels: kind/enhancement

#42 feat: Save reports to cluster, add new `--print` flag to print them as JSON
  CONTRIBUTING.md
  README.md
  cmd/root.go
  internal/report/report.go
  internal/report/report_test.go
  internal/report/store.go
  internal/report/store_test.go
  internal/resources/fetcher.go
  internal/scanner/scanner.go
Labels: kind/enhancement

#47 feat: Set PolicyReportResult fields
  .github/workflows/reusable-container-image.yml
  Makefile
  internal/report/report.go
  internal/report/store.go
  internal/scanner/scanner.go
Labels: kind/chore, kind/enhancement

#51 feat: reuse report results.
  internal/constants/constants.go
  internal/report/constants.go
  internal/report/report.go
  internal/report/report_test.go
  internal/report/store.go
  internal/report/store_test.go
  internal/scanner/scanner.go
  internal/scanner/scanner_test.go
Labels: kind/enhancement

#56 fix: publish release drafter draft release.
  .github/release-drafter.yml
Labels: kind/bug, area/ci
