Repository kubewarden/audit-scanner, pull requests merged in 2023-09, with the labels that each got.

#106 chore(deps): be explicit about the GH actions versions
  .github/workflows/ci.yml
  .github/workflows/container-image.yml
  .github/workflows/fossa.yml
  .github/workflows/release-drafter.yml
  .github/workflows/release.yml
  .github/workflows/sbom.yml
  .github/workflows/sign-image.yml
Labels: kind/chore, area/dependencies

#103 refactor!: Rename `--print` flag to `--output-scan`
  CONTRIBUTING.md
  cmd/root.go
Labels: kind/breaking-change

#123 chore: update controller-runtime.
  go.mod
  go.sum
  internal/report/store_test.go
Labels: kind/chore
