Repository kubewarden/audit-scanner, pull requests merged in 2023-07, with the labels that each got.

#57 Updates cosign to v2.
  .github/workflows/container-build.yml
  .github/workflows/release.yml
  .github/workflows/reusable-container-image.yml
Labels: kind/enhancement, area/ci

#58 feat: use ObjectSelector to fetch the resources.
  internal/resources/fetcher.go
  internal/resources/fetcher_test.go
Labels: kind/feature

#72 fix: enable release candidates when required
  .github/workflows/release.yml
Labels: kind/bug, area/ci

#75 feat: Add `--insecure-ssl`, `--filepath-cacert` flags, consume ca cert
  cmd/root.go
  internal/policies/fetcher.go
  internal/policies/fetcher_test.go
  internal/resources/fetcher.go
  internal/scanner/scanner.go
Labels: kind/feature
