Repository kubewarden/audit-scanner, pull requests merged in 2024-09, with the labels that each got.

#367 build(deps): bump kubewarden-controller dependency to v1.17.0-rc2
  go.mod
  go.sum
Labels: area/dependencies

#369 fix: Correctly log errors on creating AdmissionReview instead of panic
  internal/report/report.go
  internal/report/report_test.go
  internal/scanner/scanner.go
Labels: kind/bug

#373 feat: support PolicyGroups
  internal/constants/constants.go
  internal/policies/client.go
  internal/policies/client_test.go
  internal/scanner/scanner.go
  internal/scanner/scanner_test.go
  internal/testutils/testutils.go
Labels: kind/feature

#377 test: add a test covering the HTTP error scenario
  internal/scanner/scanner_test.go
Labels: kind/tech-debt

#378 build(deps): bump kubewarden-controller to v1.17.0-rc3
  go.mod
  go.sum
Labels: area/dependencies

#382 build(deps): bump kubewarden-controller to v1.17.0
  go.mod
  go.sum
Labels: area/dependencies
