Repository kubewarden/audit-scanner, pull requests merged in 2024-07, with the labels that each got.

#312 fix: Skip policies with unknown GVR or policy-server URL
  internal/policies/client.go
  internal/policies/client_test.go
  internal/scanner/scanner.go
  internal/scanner/scanner_test.go
Labels: kind/bug

#318 feat: use stricter go linter configuration.
  .github/workflows/ci.yml
  .golangci.yml
  Makefile
  cmd/root.go
  internal/policies/client.go
  internal/report/store_test.go
  internal/scanner/scanner.go
  internal/scanner/scanner_test.go
Labels: kind/feature

#327 chore: update kubewarden-controller version to v1.15.0-rc1
  go.mod
  go.sum
  internal/policies/client.go
  internal/policies/client_test.go
  internal/report/report.go
  internal/report/report_test.go
  internal/report/store_test.go
  internal/scanner/scanner.go
  internal/scanner/scanner_test.go
  internal/scheme/scheme.go
  internal/testutils/testutils.go
Labels: kind/chore

#331 build(deps): bump kubewarden-controller dependency to v1.15.0-rc3
  go.mod
  go.sum
Labels: area/dependencies
