Repository kubewarden/audit-scanner, pull requests merged in 2024-12, with the labels that each got.

#428 fix: Consume digest from step output
  .github/workflows/release.yml
Labels: kind/bug

#436 build(deps): bump x/net to v0.33.0
  go.mod
  go.sum
Labels: area/dependencies

#437 chore(deps): update kubewarden-controller
  go.mod
  go.sum
Labels: kind/chore, area/dependencies
