Repository kubewarden/audit-scanner, pull requests merged in 2024-03, with the labels that each got.

#214 fix(report): Result field is optional.
  internal/report/report.go
  internal/report/report_test.go
  internal/scanner/scanner_test.go
Labels: kind/bug

#221 chore(report): constants should be private
  internal/report/constants.go
  internal/report/report.go
  internal/report/report_test.go
Labels: kind/chore

#220 feat: parallel audit requests
  go.mod
  go.sum
  internal/scanner/scanner.go
Labels: kind/feature, kind/enhancement

#224 fix(ci): set prerelease and latest flag properly.
  .github/workflows/release.yml
Labels: kind/bug

#229 fix: add policy name and policy namespace to result properties
  README.md
  internal/report/constants.go
  internal/report/report.go
  internal/report/report_test.go
Labels: kind/enhancement

#231 feat: Add new `kubewarden.io/policyreport-version: v2` label
  internal/report/constants.go
  internal/report/report.go
  internal/report/report_test.go
Labels: kind/feature

#235 fix: wildcard resources not being skipped
  internal/policies/client.go
  internal/policies/client_test.go
  internal/testutils/testutils.go
Labels: kind/bug
