Repository kubewarden/audit-scanner, pull requests merged in 2025-04, with the labels that each got.

#509 fix: policy server service labels changed.
  go.mod
  go.sum
  internal/policies/client.go
  internal/policies/client_test.go
  internal/scanner/scanner_test.go
Labels: kind/bug

#507 chore: remove zerlog in favour of slog
  cmd/logging.go
  cmd/root.go
  go.mod
  go.sum
  internal/k8s/client.go
  internal/k8s/client_test.go
  internal/log/level.go
  internal/policies/client.go
  internal/policies/client_test.go
  internal/report/store.go
  internal/report/store_test.go
  internal/scanner/config.go
  internal/scanner/scanner.go
  internal/scanner/scanner_test.go
Labels: kind/chore

#519 chore: updates kubewarden-controller dep to v1.24.0-rc3.
  go.mod
  go.sum
Labels: kind/chore

#522 chore(deps): update kubewarden-controller
  go.mod
  go.sum
Labels: kind/chore, area/dependencies
